import type { Metadata } from 'next'
import { dark } from '@clerk/themes'
import {
  ClerkProvider,
} from '@clerk/nextjs'
import './globals.css'
import Navbar from '@/components/Navbar/Navbar'
import { Toaster } from "@/components/ui/sonner"


export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider appearance={
      { baseTheme: dark }
    }>
      <html lang="en">
        <head>
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
          <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap" rel="stylesheet" />
          <link href="https://fonts.googleapis.com/css2?family=Inter+Tight:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet" />
          <link href="https://www.nerdfonts.com/assets/css/webfont.css" rel="stylesheet" />
        </head>
        <body className={` antialiased bg-[var(--friday-background)] dark nf`}>
          <Navbar />
          <div className=''>
            {children}
          </div>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  )
}
